# Generated by Django 3.1.5 on 2021-02-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210222_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Stores',
        ),
    ]
