# Generated by Django 3.1.5 on 2021-02-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210222_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.report'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='complaint',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Notification Sent', 'Notification Sent'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Fashion', 'Fashion')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
