# Generated by Django 3.1.5 on 2021-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210301_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFBChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
