# Generated by Django 3.1.6 on 2021-03-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210311_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reportID',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='tenantName',
            new_name='phone',
        ),
    ]
