# Generated by Django 3.1.6 on 2021-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210313_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Tenant',
            new_name='tenantName',
        ),
    ]
