# Generated by Django 3.1.6 on 2021-03-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_order_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='complaint',
            new_name='rectificationNeeded',
        ),
    ]
