# Generated by Django 3.1.6 on 2021-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210313_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
