# Generated by Django 3.1.6 on 2021-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_store_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='audit_date',
            field=models.DateField(null=True, verbose_name='dd/mm/yyyy'),
        ),
    ]
