# Generated by Django 3.1.6 on 2021-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210313_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
