# Generated by Django 3.1.6 on 2021-03-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210313_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='tenantName',
            new_name='tenant_name',
        ),
    ]
