# Generated by Django 3.1.6 on 2021-03-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210313_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement',
            new_name='announcement_title',
        ),
    ]
