# Generated by Django 3.1.6 on 2021-03-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210313_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tenant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.store'),
        ),
    ]
