# Generated by Django 3.1.6 on 2021-03-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210313_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tenant_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
