# Generated by Django 3.1.6 on 2021-03-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210322_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='issue',
        ),
        migrations.AddField(
            model_name='order',
            name='covid_compliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.covidcompliancechecklist'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('FB', 'FB'), ('Non-FB', 'Non-FB')], max_length=200, null=True),
        ),
    ]
