# Generated by Django 3.1.6 on 2021-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_order_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
