# Generated by Django 3.1.7 on 2021-03-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_order_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.store'),
        ),
    ]
