# Generated by Django 3.1.7 on 2021-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210323_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
