# Generated by Django 3.1.7 on 2021-03-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_report_report_number'),
        ('accounts', '0032_order_uploaded_image'),
    ]

    operations = [
    ]
