# Generated by Django 3.1.7 on 2021-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_report_total_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='issue',
        ),
        migrations.AddField(
            model_name='report',
            name='issue',
            field=models.ManyToManyField(to='accounts.NonFBChecklist'),
        ),
    ]
