# Generated by Django 3.1.7 on 2021-03-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210323_1622'),
        ('accounts', '0034_merge_20210323_1610'),
    ]

    operations = [
    ]
