# Generated by Django 3.1.6 on 2021-03-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_merge_20210323_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uploaded_image',
        ),
    ]
