# Generated by Django 3.1.7 on 2021-03-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_merge_20210323_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='issue',
            new_name='compliance',
        ),
    ]
