# Generated by Django 3.1.6 on 2021-03-23 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_order_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upload_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
