# Generated by Django 3.1.7 on 2021-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_order_upload_image'),
        ('accounts', '0040_remove_report_total_checked'),
    ]

    operations = [
    ]
