# Generated by Django 3.1.7 on 2021-03-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_statistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistics_page',
        ),
        migrations.RenameField(
            model_name='statistics_page',
            old_name='statistics',
            new_name='statistics_name',
        ),
    ]
