# Generated by Django 3.0.6 on 2021-04-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auditscore'),
        ('accounts', '0044_auto_20210326_1047'),
    ]

    operations = [
    ]
