# Generated by Django 3.1.7 on 2021-04-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210326_1047'),
        ('accounts', '0042_auditscore'),
    ]

    operations = [
    ]
