# Generated by Django 3.1.7 on 2021-04-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_fbreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='NonFBReport',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='report',
            new_name='nonfbreport',
        ),
        migrations.AddField(
            model_name='order',
            name='fbreport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fbreport'),
        ),
    ]
