# Generated by Django 3.2 on 2021-04-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_covidreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='score_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
