# Generated by Django 3.2 on 2021-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_covidreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fbreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nonfbreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
