# Generated by Django 3.2 on 2021-04-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_order_score_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='score_number',
        ),
        migrations.AddField(
            model_name='covidreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fbreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nonfbreport',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
