# Generated by Django 3.0.6 on 2021-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210421_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidreport',
            name='report_number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidreport',
            name='score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
