# Generated by Django 3.2 on 2021-04-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210421_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fbreport',
            new_name='FB_Report',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='nonfbreport',
            new_name='Non_FB_Report',
        ),
        migrations.AddField(
            model_name='order',
            name='Covid_Compliance_Report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.covidreport'),
        ),
    ]
